
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:lion_print_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:azamjon1999}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties.hibernate.enable_lazy_load_no_trans: true

jwt:
  secret: ${JWT_SECRET:635266556A586E3272357538782F413F4428472B4B6250645367566B50}
